// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlE1A0P0MYwi6wHnWEixyAZRuCnXnAyrQ',
    appId: '1:1097787238772:web:27bc555d79a3b7b683a421',
    messagingSenderId: '1097787238772',
    projectId: 'ucc-quiz-portal',
    authDomain: 'ucc-quiz-portal.firebaseapp.com',
    storageBucket: 'ucc-quiz-portal.appspot.com',
    measurementId: 'G-80SXJGWXWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ7PtJ6OrKi4URoKXMk4YhDoOwn89GlRA',
    appId: '1:1097787238772:android:8ed45ccc8311a2d783a421',
    messagingSenderId: '1097787238772',
    projectId: 'ucc-quiz-portal',
    storageBucket: 'ucc-quiz-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7jDVLrM_45zFm7yWXhfS7VokbU9NyZuQ',
    appId: '1:1097787238772:ios:472d59db7189281a83a421',
    messagingSenderId: '1097787238772',
    projectId: 'ucc-quiz-portal',
    storageBucket: 'ucc-quiz-portal.appspot.com',
    iosBundleId: 'gh.edu.ucc.quiz.portal',
  );
}
